name: trigger_workflow

on:
  pull_request:
    types:
      - closed

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{github.event.pull_request.labels.*.name[0]}}"
  call-workflow:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    uses: ./.github/workflows/release.yml
